# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 003cfd1318930f1f74e1c53ab41603441e100719d7df6624135c51af669bdeab5e7cbf995649a0ef11b09561c85b3309e7d3dc94fe3d216134ac8903c53a3657

test:
  secret_key_base: 16beea9d6b0f00bee3cf60fa5de3d0360176449fd54b275ecfa9f70302203566b11c7155f00180d72a76214742e05ee288e23266483b1103b7aca1f383e9eb5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
